# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATASOURCE (H2)
# ===============================
spring.datasource.url=jdbc:h2:mem:bci-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# SQL INIT (evita error data.sql)
# ===============================
spring.sql.init.mode=never

# ===============================
# JWT CONFIG
# ===============================
security.jwt.secret=bci-super-secure-jwt-secret-key-256-bits!!
security.jwt.expiration=3600000

# ===============================
# PASSWORD REGEX (BCI)
# ===============================
security.password.regex=^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{8,}$

# ===============================
# SWAGGER
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html